### ISSUE TITLE
Failed to export

### ISSUE THREAD

**Issue by emperorhunterr** [thomascgray/opr-af-to-tts#30]
I don't know of any better place to put this but it has been infrequent with generating my army. Have done it succesfully before but stopped working now with same way of doing it. Playing Dwarfs at the moment. Has just been saying "Army Forge failed to export list. Sorry!" This is the link used.    https://army-forge.onepagerules.com/share?id=5vhz5dG0oqCa&name=Drinkers_Guild

**Comment by thomascgray** [comment]
Ah, unfortunately that error is when https://army-forge.onepagerules.com _itself_ fails to export the list.

We need Army Forge to export the list so that this tool can do an _import_ to get all the data.

When you hit the army forge export link with your list ID, it seems army forge is throwing some kind of internal error?
https://army-forge.onepagerules.com/api/tts?id=5vhz5dG0oqCa

Unfortunately, theres nothing I can do about this. Maybe your list is triggering this known army forge bug? https://github.com/opr-official/army-forge-issues/issues/8

In the mean time, I'll try and improve the error messaging to make it more clear that this is a bug thats happening on army forge's end.
