### ISSUE TITLE
Duplicate Weapon(s)

### ISSUE THREAD

**Issue by JustNerro** [thomascgray/opr-af-to-tts#43]
sometimes weapons are listed multiple times

no specific step that I could think of, it happens every time, as I can recall, to Blessed Sisters' Hunter Missiles, and I'm sure to other armies/units too, to the point that I should always have to check and make the other one 0 to disable it. Also, the duplicate is formatted differently, as you can see in the screenshot. The stats are part of the weapon name instead of smaller text in the list.

Exhibit 1: Blessed Sisters' Battle Tank Hunter Missile
![image](https://github.com/thomascgray/opr-af-to-tts/assets/66056323/d4246ddc-8c98-4991-a981-0356d088abfb)
![image](https://github.com/thomascgray/opr-af-to-tts/assets/66056323/cfa498ff-c2c5-4be8-adb9-06784331c33c)
[Link to the AF list](https://army-forge.onepagerules.com/share?id=XG24Yv8JF2dX&name=Blessed_Sisters%203K).
[Link to the importer list](https://opr-af-to-tts.netlify.app/.netlify/functions/save-list?listId=JLjfLvaqRgBoXauhgrFMl).

Exhibit 2: Darl Elf's Gene-Warrior CCW/Double CCW
![image](https://github.com/thomascgray/opr-af-to-tts/assets/66056323/8ecebbd2-0c90-42a6-8c03-5ffb7620e725)
![image](https://github.com/thomascgray/opr-af-to-tts/assets/66056323/3d18f9a2-7b4f-479a-af67-63571bedfc43)
![image](https://github.com/thomascgray/opr-af-to-tts/assets/66056323/b07a4bf1-93c7-42fb-8b94-088a7f7bae2b)

**Comment by thomascgray** [comment]
Ahh, this took a comically long time to track down.

So the tl;dr is that the output is based on some structured internal data that Army Forge spits out.

And my app takes into account 2 different parts of this structured data in order to generate a model's stuff:

- `loadout`
- `unitUpgrades`

and _sometimes_, for reasons unknown to me, the same thing appears in both of those places!

So my code does something similar to "OK, add all the `loadout` to the models stuff. Now loop over the unit upgrades, and add them _if they're not already added from the loadout_"

Unfortunately, Army Forge doesn't give me any IDs to compare, so I am forced to compare raw name values. And, well...

![image](https://github.com/thomascgray/opr-af-to-tts/assets/5067968/0c664cf7-3dec-4c00-b6b4-548c5b1b9774)

the item from loadout is called `Hunter Missile`, the item from `unitUpgrades` is called `Hunter Missiles` (note the pluralisation)

I'm going to try and work out a way to make this check better, but for now, I'm afraid this is a pure Army Forge data issue! Will update this issue if I get something working consistently.

**Comment by thomascgray** [comment]
OK, closed as of https://github.com/thomascgray/opr-af-to-tts/pull/45 see that PR for details.

Lemme know if you spot any more of this bug! Thanks for reporting
