### ISSUE TITLE
Toughnes of units isn't added when I import them to tts

### ISSUE THREAD

**Issue by CosminBudurovici** [thomascgray/opr-af-to-tts#48]
After the last patch whenever I try to import something with tough(3) or more the toughness doesn't shou up. Another minor bug is that the text for phosfor (Machine cults) isn't showing

**Comment by thomascgray** [comment]
Hey,

Sorry to hear you're having problems.

When you say "last patch", I guess theres been an army forge patch or something you mean?

Could you post here the URLs to your army(s), and maybe even some screenshots of exactly what is happening? And what game systems, etc.

E.g if the Tough (3) appearing in the webapp, but not in-game? Or not in the webapp at all?

Cheers!

**Comment by thomascgray** [comment]
hey, thanks for letting me know about this! Fixed as of https://github.com/thomascgray/opr-af-to-tts/commit/6e77279f45cc54d0dc94be818e2aeaa9e6a517a6

- the tough thing (and other special rules) are now patched
- the missing "Phosphor" is unfortunately happening on army forge's end. Not much I can do about that! I have made it so that if the description is missing, it'll say "[[Rule description missing in Army Forge data!]]" instead of just being blank
